** CNX dbWebServCedis **


-- Tabla Categoría
CREATE TABLE categoria (
   id_categoria NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY  PRIMARY KEY,
   nombre VARCHAR2(100) NOT NULL,
   descripcion VARCHAR2(255)
);

-- Tabla Producto
CREATE TABLE producto (
   id_producto NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY ,
   nombre VARCHAR2(100) NOT NULL,
   precio NUMBER(10,2) NOT NULL,
   stock NUMBER DEFAULT 0,
   id_categoria NUMBER NOT NULL,
   CONSTRAINT fk_producto_categoria FOREIGN KEY (id_categoria) REFERENCES categoria(id_categoria)
);

-- Tabla Ventas
CREATE TABLE ventas (
   id_venta NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
   id_producto NUMBER NOT NULL,
   cantidad NUMBER NOT NULL,
   fecha_venta DATE DEFAULT SYSDATE,
   total NUMBER(10,2) NOT NULL,
   CONSTRAINT fk_ventas_producto FOREIGN KEY (id_producto) REFERENCES producto(id_producto)
);

-- Tabla usuario
CREATE TABLE usuarios (
   id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   nombre VARCHAR2(100) NOT NULL,
   email VARCHAR2(150) UNIQUE NOT NULL,
   password VARCHAR2(255) NOT NULL,
   rol VARCHAR2(20) DEFAULT 'CLIENTE' CHECK (rol IN ('ADMIN', 'VENDEDOR', 'CLIENTE')),
   fecha_registro DATE DEFAULT SYSDATE,
   activo CHAR(1) DEFAULT 'Y' CHECK (activo IN ('Y', 'N'))
);
--add field y fk id_usuario to table usuarios
ALTER TABLE ventas ADD (id_usuario NUMBER NOT NULL, 
CONSTRAINT fk_ventas_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario));
